import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.*;
import java.util.Vector;

/**
 * Created by hyeon-yeong on 2017. 1. 27..
 */
public class contentForm {
    private static JFrame frame;
    private JPanel mainContent;
    private JPanel top;
    private JButton LOGOUTbtn;
    private JPanel namePanel;
    private JLabel nameLabel;
    private JLabel welcomeMsg;
    private JPanel content;
    private JPanel sideMenu;
    private JButton makeFolderBtn;
    private JList list;
    private JPanel center;
    private JButton addBtn;
    private JButton deleteBtn;
    private JPanel btn;
    private JPanel mainC;

    private JTable mainTable;
    private JScrollPane scroll;
    private JOptionPane input;
    private DefaultTableModel dtm;
    Object[][] rowData;
    Vector vec;

    public contentForm(ConnectServer cs, String userName) {
        frame = new JFrame("File Manager");
        frame.setContentPane(mainContent);
        frame.setSize(800, 400);
        frame.setLocation(300, 200);
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frame.setVisible(true);
        vec = new Vector();
        nameLabel.setText(userName);

        makeFolderBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                mainTable = new JTable();
                String folderName = JOptionPane.showInputDialog(null, "폴더이름을 입력해 주세요");
                vec.addElement(folderName);
                list.setListData(vec);
                list.setSelectedIndex(0);
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainContent = new JPanel();
        mainContent.setLayout(new BorderLayout(0, 0));
        mainContent.setBackground(new Color(-1));
        mainContent.setForeground(new Color(-12300455));
        mainContent.setPreferredSize(new Dimension(100, 30));
        top = new JPanel();
        top.setLayout(new BorderLayout(0, 0));
        top.setBackground(new Color(-79671));
        top.setPreferredSize(new Dimension(0, 30));
        mainContent.add(top, BorderLayout.NORTH);
        LOGOUTbtn = new JButton();
        LOGOUTbtn.setBackground(new Color(-79671));
        LOGOUTbtn.setText("LOGOUT");
        top.add(LOGOUTbtn, BorderLayout.EAST);
        namePanel = new JPanel();
        namePanel.setLayout(new BorderLayout(0, 0));
        namePanel.setBackground(new Color(-79671));
        namePanel.setPreferredSize(new Dimension(150, 0));
        top.add(namePanel, BorderLayout.WEST);
        nameLabel = new JLabel();
        nameLabel.setFont(new Font("Monospaced", Font.BOLD, 16));
        nameLabel.setForeground(new Color(-12300455));
        nameLabel.setPreferredSize(new Dimension(80, 16));
        nameLabel.setText(" 이현영");
        namePanel.add(nameLabel, BorderLayout.WEST);
        welcomeMsg = new JLabel();
        welcomeMsg.setForeground(new Color(-12300455));
        welcomeMsg.setText("님 반갑습니다");
        namePanel.add(welcomeMsg, BorderLayout.CENTER);
        content = new JPanel();
        content.setLayout(new BorderLayout(0, 0));
        content.setForeground(new Color(-12300455));
        content.setOpaque(false);
        mainContent.add(content, BorderLayout.CENTER);
        sideMenu = new JPanel();
        sideMenu.setLayout(new BorderLayout(0, 0));
        sideMenu.setAutoscrolls(true);
        sideMenu.setBackground(new Color(-2820870));
        sideMenu.setOpaque(true);
        sideMenu.setPreferredSize(new Dimension(150, 0));
        content.add(sideMenu, BorderLayout.WEST);
        makeFolderBtn = new JButton();
        makeFolderBtn.setBackground(new Color(-2820870));
        makeFolderBtn.setForeground(new Color(-12300455));
        makeFolderBtn.setHideActionText(false);
        makeFolderBtn.setOpaque(true);
        makeFolderBtn.setText("폴더 만들기");
        sideMenu.add(makeFolderBtn, BorderLayout.SOUTH);
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setPreferredSize(new Dimension(271, 300));
        sideMenu.add(scrollPane1, BorderLayout.NORTH);
        list = new JList();
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        list.setModel(defaultListModel1);
        list.setOpaque(true);
        list.setPreferredSize(new Dimension(0, 350));
        scrollPane1.setViewportView(list);
        center = new JPanel();
        center.setLayout(new BorderLayout(0, 0));
        center.setOpaque(false);
        content.add(center, BorderLayout.CENTER);
        btn = new JPanel();
        btn.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        btn.setBackground(new Color(-1));
        btn.setOpaque(false);
        btn.setPreferredSize(new Dimension(0, 40));
        center.add(btn, BorderLayout.NORTH);
        addBtn = new JButton();
        addBtn.setBackground(new Color(-1));
        addBtn.setText("파일 추가");
        btn.add(addBtn);
        deleteBtn = new JButton();
        deleteBtn.setBackground(new Color(-1));
        deleteBtn.setText("파일 삭제");
        btn.add(deleteBtn);
        mainC = new JPanel();
        mainC.setLayout(new BorderLayout(0, 0));
        mainC.setOpaque(false);
        center.add(mainC, BorderLayout.CENTER);
        nameLabel.setLabelFor(scrollPane1);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainContent;
    }


    /**
     * @noinspection ALL
     */

}
